services:
  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_duration=on",
        "-c",
        "log_min_duration_statement=0",
      ]
    volumes:
      - postgresql:/var/lib/postgresql

volumes:
  postgresql:
